name: chocolatine

on: [push, workflow_dispatch]

env:
  MIRROR_URL: git@github.com:EpitechPromo2026/B-DOP-200-NCY-2-1-chocolatine-hugo.bunelier.git

jobs:
  check_repo:
    name: "Check if the repo is clean"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: clean
        run: |
          UNWANTED_FILES=$(find . -type f -not -path "./git/*" -wholename "*/tmp*" -or -name "*.o" -or -name "*.a" -or -name "*.gcno" -or -name "*.gcda" -or -name "*gcov" -or -name "*pain_au_chocolat*")
          for FILE  in $UNWANTED_FILES; do
            echo "::error file=${FILE#./}, title=Unwanted file detected::${FILE#./}"
          done
          if [[ -z "$UNWATED_FILES" ]]
          then
            echo empty list
          else
            exit 1
          fi

  to_gitlab:
    name: "Push to mirror"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.FDP }}
