name: repository size

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
      - uses: actions/checkout@v3

      - name: Branch name
      - run: echo $(git branch --show-current)

      - name: branch size
      - run: du -skh --exclude=".git"
