name: repository size

on: [push, workflow_dispatch]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Branch name
        run: echo $(git branch --show-current)

      - name: branch size
        run: |
          du -skh --exclude=".git"
